spring.application.name=taskmanagement
spring.main.allow-bean-definition-overriding=true

# Datasource

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:14333;databaseName=task_management;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Password@123}

# JPA

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

# Server

server.port=${SERVER_PORT:8080}

# Spring Security default user

spring.security.user.name=${SPRING_SECURITY_USER_NAME:admin}
spring.security.user.password=${SPRING_SECURITY_USER_PASSWORD:123123}

# JWT

jwt.secret=${JWT_SECRET:TaskManagementSecretKey2026SpringBootJavaProject}
jwt.expiration=${JWT_EXPIRATION:86400000}

# Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phonghuuho204@gmail.com
spring.mail.password=yekejrfcibshinom
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload

file.upload-dir=${FILE_UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=${MULTIPART_MAX_FILE_SIZE:20MB}
spring.servlet.multipart.max-request-size=${MULTIPART_MAX_REQUEST_SIZE:20MB}


# Actuator for Kubernetes probes
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true