apiVersion: v1
kind: ConfigMap
metadata:
  name: taskapp-config
data:
  db-username: "sa"
  db-url: "jdbc:sqlserver://sql-server:1433;databaseName=task_management;encrypt=true;trustServerCertificate=true"