apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
  namespace: taskmanagement
  labels:
    app.kubernetes.io/name: taskmanagement
type: Opaque
stringData:
  db-password: "Password@123"
  jwt-secret: "TaskManagementSecretKey2026SpringBootJavaProject"
  mail-password: "yekejrfcibshinom"
