apiVersion: v1
kind: Secret
metadata:
  name: taskapp-secret
type: Opaque
stringData:
  db-password: "Password@123"
  jwt-secret: "TaskManagementSecretKey2026SpringBootJavaProject"
  mail-password: "your-mail-password"
