apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-server-pvc
  namespace: taskmanagement
  labels:
    app.kubernetes.io/name: taskmanagement
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
